# Generated by Django 5.1.2 on 2024-10-28 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('genre', models.CharField(max_length=100)),
                ('availability', models.BooleanField(default=True)),
                ('publication_date', models.DateField()),
                ('summary', models.CharField(max_length=1000)),
                ('edition', models.CharField(max_length=100)),
            ],
        ),
    ]
